In [427]:
import numpy as np
import pandas as pd

In [428]:
df=pd.read_csv(r'maharashtra_exit_poll_survey_2024 (1).csv')

In [429]:
df.head()

,respondent_id,interview_datetime,surveyor_id,ac_number,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,MH2024018299,2024-11-20 09:39,SV039,148,Marathwada,Beed,Rural,Male,26-35,NaN,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,MH2024004932,2024-11-20 04:28,SV080,156,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,MH2024014706,2024-11-20 02:58,SV017,240,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,NaN,Good Work - Shinde Govt
3,MH2024020177,2024-11-20 11:45,SV005,22,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,VBA,NaN,For Uddhav Thackeray
4,MH2024003243,2024-11-20 09:08,SV047,91,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,NaN

In [430]:
df.isnull().sum()

respondent_id            0
interview_datetime       0
surveyor_id           1733
ac_number                0
region                   0
district                 0
geography                0
gender                   0
age_band                 0
age                   1786
caste                 1800
occupation               0
voted_alliance           0
voted_party              0
cm_preference         1753
voting_reason         1710
dtype: int64

In [431]:
df.shape

(35313, 16)

In [432]:
df=df.drop("interview_datetime",axis =1)
df

,respondent_id,surveyor_id,ac_number,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,MH2024018299,SV039,148,Marathwada,Beed,Rural,Male,26-35,NaN,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,MH2024004932,SV080,156,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,MH2024014706,SV017,240,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,NaN,Good Work - Shinde Govt
3,MH2024020177,SV005,22,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,VBA,NaN,For Uddhav Thackeray
4,MH2024003243,SV047,91,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35308,MH2024023750,SV077,237,Vidarbha,Gondiya,Rural,Female,36-50,40.0,SC,Skilled Professional,MVA,CONG,NaN,Good Work - Centre Govt
35309,MH2024021573,SV045,13,Western Maharashtra,Pune,Rural,Male,61+,79.0,Maratha,Labour,MVA,NCP (SP),Jayant Patil,For Uddhav Thackeray
35310,MH2024034537,SV073,116,Vidarbha,Buldhana,Rural,Male,51-60,59.0,Other OBC,Farmer,Others,BSP,Eknath Shinde,Ladki Bahin Benefit
35311,MH2024023588,SV071,28,Marathwada,Jalna,Rural,Male,36-50,49.0,Maratha,Housewife,Others,BSP,Uddhav Thackeray,Party Loyalist
35312,MH2024029314,SV017,88,Western Maharashtra,Kolhapur,Urban,Male,51-60,52.0,Maratha,Labour,MVA,SHS (UBT),Others/DK,Development

In [433]:
df.describe()

         ac_number           age
count  35313.00000  33527.000000
mean     145.52601     42.943926
std       88.38572     26.685639
min       -1.00000      0.000000
25%       72.00000     30.000000
50%      145.00000     40.000000
75%      217.00000     53.000000
max      999.00000    999.000000

In [434]:
df.duplicated().sum()

np.int64(303)

In [435]:
df.corr(numeric_only=True)

           ac_number       age
ac_number   1.000000  0.000452
age         0.000452  1.000000

In [436]:
df[df.duplicated()]

,respondent_id,surveyor_id,ac_number,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
2261,MH2024010811,SV082,199,Vidarbha,Amravati,Rural,Female,26-35,30.0,Others,Farmer,MVA,NCP (SP),Others/DK,Inflation
2758,MH2024008248,SV057,196,Vidarbha,Chandrapur,Rural,Male,26-35,26.0,Kunbi,Skilled Professional,Maha Yuti,BJP,Others/DK,Unemployment
2771,MH2024029875,SV039,107,Western Maharashtra,Solapur,Rural,Female,26-35,31.0,ST,Unemployed,Maha Yuti,NCP (AP),Uddhav Thackeray,Inflation
2916,MH2024004942,SV080,123,Western Maharashtra,Sangli,Urban,Female,18-25,23.0,Muslim,Housewife,MVA,CONG,Uddhav Thackeray,Development
3475,MH2024000439,SV065,201,Marathwada,Aurangabad,Urban,Male,18-25,24.0,Maratha,Farmer,Others,Others,Sharad Pawar,Change
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35161,MH2024019849,SV034,243,Vidarbha,Akola,Rural,Female,36-50,42.0,Other OBC,Labour,Maha Yuti,BJP,Eknath Shinde,Party Loyalist
35169,MH2024007435,SV054,163,Vidarbha,Nagpur,Rural,Male,36-50,39.0,ST,Labour,MVA,CONG,Eknath Shinde,Ladki Bahin Benefit
35252,MH2024027174,SV058,168,North Maharashtra,Nashik,Rural,Male,36-50,47.0,Muslim,Farmer,MVA,NCP (SP),Eknath Shinde,MLA Candidate
35285,MH2024030619,SV071,105,Konkan & Thane,Palghar,Urban,Female,26-35,32.0,SC,Others,MVA,SHS (UBT),Eknath Shinde,Development
35300,MH2024008437,NaN,60,Vidarbha,Gondiya,Urban,Male,18-25,25.0,Maratha,Unemployed,Maha Yuti,SHS (Shinde),Any CONG candidate,Development

In [437]:
df=df.drop_duplicates()

In [438]:
df

,respondent_id,surveyor_id,ac_number,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,MH2024018299,SV039,148,Marathwada,Beed,Rural,Male,26-35,NaN,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,MH2024004932,SV080,156,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,MH2024014706,SV017,240,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,NaN,Good Work - Shinde Govt
3,MH2024020177,SV005,22,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,VBA,NaN,For Uddhav Thackeray
4,MH2024003243,SV047,91,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35308,MH2024023750,SV077,237,Vidarbha,Gondiya,Rural,Female,36-50,40.0,SC,Skilled Professional,MVA,CONG,NaN,Good Work - Centre Govt
35309,MH2024021573,SV045,13,Western Maharashtra,Pune,Rural,Male,61+,79.0,Maratha,Labour,MVA,NCP (SP),Jayant Patil,For Uddhav Thackeray
35310,MH2024034537,SV073,116,Vidarbha,Buldhana,Rural,Male,51-60,59.0,Other OBC,Farmer,Others,BSP,Eknath Shinde,Ladki Bahin Benefit
35311,MH2024023588,SV071,28,Marathwada,Jalna,Rural,Male,36-50,49.0,Maratha,Housewife,Others,BSP,Uddhav Thackeray,Party Loyalist
35312,MH2024029314,SV017,88,Western Maharashtra,Kolhapur,Urban,Male,51-60,52.0,Maratha,Labour,MVA,SHS (UBT),Others/DK,Development

In [439]:
df.duplicated().sum()

np.int64(0)

In [440]:
df.describe()

          ac_number           age
count  35010.000000  33241.000000
mean     145.582405     42.937998
std       88.428221     26.754044
min       -1.000000      0.000000
25%       72.000000     30.000000
50%      145.000000     40.000000
75%      217.750000     53.000000
max      999.000000    999.000000

In [441]:
df['gender'].unique()
gender_map = {
    'M':'Male','m':'Male','males':'Male','mal':'Male',
    'F':'Female','f':'Female','females':'Female','femal':'Female'
}
df['gender'] = df['gender'].str.lower().map(
    lambda x: gender_map.get(x, x.title()) if pd.notna(x) else x
)

C:\Users\astit\AppData\Local\Temp\ipykernel_6200\1293117184.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].str.lower().map(

In [442]:
caste_map = {
    'maratha':'Maratha','marathas':'Maratha','marata':'Maratha',
    'muslim':'Muslim','mulsim':'Muslim',
    'other obc':'Other OBC','otherobc':'Other OBC','othr obc':'Other OBC','other_obc':'Other OBC',
    'sc':'SC','s.c.':'SC',
    'st':'ST','s.t.':'ST',
    'nt_vj':'NT_VJ','nt|vj':'NT_VJ',
    'kunbi':'Kunbi','other general':'Other General','others':'Others'
}
valid_castes = ['SC','ST','NT_VJ','Muslim','Kunbi','Other OBC','Maratha','Other General','Others']
df['caste'] = (df['caste']
    .str.strip()
    .str.lower()
    .map(lambda x: caste_map.get(x, x) if pd.notna(x) else x)
)
df['caste'] = df['caste'].where(df['caste'].isin(valid_castes), other=np.nan)

C:\Users\astit\AppData\Local\Temp\ipykernel_6200\2068292653.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['caste'] = (df['caste']
C:\Users\astit\AppData\Local\Temp\ipykernel_6200\2068292653.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['caste'] = df['caste'].where(df['caste'].isin(valid_castes), other=np.nan)

In [443]:
df['caste'].value_counts()

caste
Other OBC        7677
Maratha          7593
SC               3660
ST               3344
Muslim           3301
Others           2966
Other General    2030
Kunbi            1643
NT_VJ            1006
Name: count, dtype: int64

In [444]:
band_range = {'18-25':(18,25),'26-35':(26,35),'36-50':(36,50),'51-60':(51,60),'61+':(61,100)}

In [445]:
df.head()

,respondent_id,surveyor_id,ac_number,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,MH2024018299,SV039,148,Marathwada,Beed,Rural,Male,26-35,NaN,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,MH2024004932,SV080,156,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,MH2024014706,SV017,240,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,NaN,Good Work - Shinde Govt
3,MH2024020177,SV005,22,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,VBA,NaN,For Uddhav Thackeray
4,MH2024003243,SV047,91,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,NaN

In [446]:
df=df.drop("ac_number",axis=1)

In [447]:
df=df.drop("surveyor_id",axis=1)
df=df.drop("respondent_id",axis=1)
df

,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,Marathwada,Beed,Rural,Male,26-35,NaN,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,NaN,Good Work - Shinde Govt
3,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,VBA,NaN,For Uddhav Thackeray
4,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
35308,Vidarbha,Gondiya,Rural,Female,36-50,40.0,SC,Skilled Professional,MVA,CONG,NaN,Good Work - Centre Govt
35309,Western Maharashtra,Pune,Rural,Male,61+,79.0,Maratha,Labour,MVA,NCP (SP),Jayant Patil,For Uddhav Thackeray
35310,Vidarbha,Buldhana,Rural,Male,51-60,59.0,Other OBC,Farmer,Others,BSP,Eknath Shinde,Ladki Bahin Benefit
35311,Marathwada,Jalna,Rural,Male,36-50,49.0,Maratha,Housewife,Others,BSP,Uddhav Thackeray,Party Loyalist
35312,Western Maharashtra,Kolhapur,Urban,Male,51-60,52.0,Maratha,Labour,MVA,SHS (UBT),Others/DK,Development

In [448]:
df.loc[~df['age'].between(18, 100), 'age'] = np.nan
band_range = {'18-25':(18,25),'26-35':(26,35),'36-50':(36,50),'51-60':(51,60),'61+':(61,100)}
def band_ok(row):
    if pd.isna(row['age']) or pd.isna(row['age_band']):
        return True
    lo, hi = band_range.get(row['age_band'], (0, 200))
    return lo <= row['age'] <= hi
mismatch = ~df.apply(band_ok, axis=1)
df.loc[mismatch, 'age'] = np.nan

In [449]:
MY_PARTIES  = ['BJP','SHS (Shinde)','NCP (AP)','JSS/RSVA/RYSP']
MVA_PARTIES = ['CONG','SHS (UBT)','NCP (SP)','SP/PWPI']
def alliance_ok(row):
    a, p = row['voted_alliance'], row['voted_party']
    if a == 'Maha Yuti' and p not in MY_PARTIES:  return False
    if a == 'MVA'and p not in MVA_PARTIES: return False
    if a == 'VBA' and p != 'VBA':           return False
    return True
bad_match = ~df.apply(alliance_ok, axis=1)
print(f'Alliance/party mismatches set to NaN: {bad_match.sum()}')
df.loc[bad_match, 'voted_party'] = np.nan

Alliance/party mismatches set to NaN: 480

In [450]:
mum_rural = (df['region'] == 'Mumbai') & (df['geography'] == 'Rural')
print(f'Mumbai-Rural fixed: {mum_rural.sum()}')
df.loc[mum_rural, 'geography'] = 'Urban'
print(f'\nFinal shape after cleaning: {df.shape}')
print('Remaining nulls:\n', df.isnull().sum())

Mumbai-Rural fixed: 2542

Final shape after cleaning: (35010, 12)
Remaining nulls:
 region               0
district             0
geography            0
gender               0
age_band             0
age               2708
caste             1790
occupation           0
voted_alliance       0
voted_party        480
cm_preference     1739
voting_reason     1697
dtype: int64

In [451]:
for col in ['gender','caste','occupation','cm_preference']:
    df[col].fillna(df[col].mode()[0], inplace=True)
df['age'] = df['age'].fillna(
    df.groupby('age_band')['age'].transform('mean').astype(np.int64)
)
df['voting_reason'].fillna('Unknown', inplace=True)

In [452]:
df

,region,district,geography,gender,age_band,age,caste,occupation,voted_alliance,voted_party,cm_preference,voting_reason
0,Marathwada,Beed,Rural,Male,26-35,30.0,Other OBC,Pvt. Service,MVA,CONG,Eknath Shinde,Change
1,Mumbai,Mumbai City,Urban,Female,36-50,46.0,Other OBC,Unemployed,MVA,CONG,Eknath Shinde,Good Work - Shinde Govt
2,Vidarbha,Nagpur,Rural,Male,36-50,45.0,Other OBC,Labour,Maha Yuti,BJP,Eknath Shinde,Good Work - Shinde Govt
3,Western Maharashtra,Kolhapur,Urban,Male,26-35,33.0,SC,Labour,MVA,NaN,Eknath Shinde,For Uddhav Thackeray
4,Vidarbha,Amravati,Rural,Female,36-50,38.0,NT_VJ,Pvt. Service,Maha Yuti,BJP,Any CONG candidate,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...
35308,Vidarbha,Gondiya,Rural,Female,36-50,40.0,SC,Skilled Professional,MVA,CONG,Eknath Shinde,Good Work - Centre Govt
35309,Western Maharashtra,Pune,Rural,Male,61+,79.0,Maratha,Labour,MVA,NCP (SP),Jayant Patil,For Uddhav Thackeray
35310,Vidarbha,Buldhana,Rural,Male,51-60,59.0,Other OBC,Farmer,Others,BSP,Eknath Shinde,Ladki Bahin Benefit
35311,Marathwada,Jalna,Rural,Male,36-50,49.0,Maratha,Housewife,Others,BSP,Uddhav Thackeray,Party Loyalist
35312,Western Maharashtra,Kolhapur,Urban,Male,51-60,52.0,Maratha,Labour,MVA,SHS (UBT),Others/DK,Development

In [453]:
df.isnull().sum()

region              0
district            0
geography           0
gender              0
age_band            0
age                 0
caste               0
occupation          0
voted_alliance      0
voted_party       480
cm_preference       0
voting_reason       0
dtype: int64